#!/bin/bash --login
#$ -cwd
#$ -e ./err/align
#$ -o ./out/align
#$ -t 1-1529

# number of tasks to be updated once the number of samples are counted

module load apps/hisat2
module load apps/samtools/1.9

export HISAT2_INDEXES="rds-asg/refs"

acc=$(sed "${SGE_TASK_ID}q;d" ./petropoulos_accessions)

fastq_file="./rds-asg/petropoulos_fastq/${acc}.fastq.gz"

#zcat $fastq_file | hisat2 -x GRCh38 -U - -S "scratch/petropoulos_sam/${acc}.sam"
samtools sort -l 9 -o "scratch/petropoulos_bam/${acc}.bam" "scratch/petropoulos_sam/${acc}.sam"
