#!/bin/bash --login
#$ -cwd
#$ -e ./err/align
#$ -o ./out/align
#$ -t 1-1529

# number of tasks to be updated once the number of samples are counted

module load apps/binapps/star/2.7.2b
module load apps/samtools/1.9

acc=$(sed "${SGE_TASK_ID}q;d" ./petropoulos_accessions)

fastq_file="./rds-asg/petropoulos_fastq/${acc}.fastq.gz"

STAR --runThreadN 1 --genomeDir rds-asg/refs/hg38_STAR_index --readFilesIn $fastq_file --readFilesCommand zcat --outFileNamePrefix scratch/petropoulos_aligned/$acc --outSAMtype BAM SortedByCoordinate
