#!/bin/bash --login
#$ -cwd
#$ -e ./err/align
#$ -o ./out/align
#$ -t 1-12

# number of tasks to be updated once the number of samples are counted

module load apps/hisat2
module load apps/samtools/1.9

export HISAT2_INDEXES="rds-asg/refs/hg38_hisat2_index"

acc=$(sed "${SGE_TASK_ID}q;d" ./peter_files)

file1="./rds-asg/peter_fastq/${acc}/${acc}_1.fq.gz"
file2="./rds-asg/peter_fastq/${acc}/${acc}_2.fq.gz"

hisat2 -x hg38 -1 "${file1}" -2 "${file2}" -S "scratch/peter_sam/${acc}.sam"
samtools sort -l 9 -o "scratch/peter_bam/${acc}.bam" "scratch/peter_sam/${acc}.sam"
