#!/bin/bash --login
#$ -cwd
#$ -e ./err/count
#$ -o ./out/count
#$ -t 1-1529

module load apps/binapps/salmon/1.3.0

acc=$(sed "${SGE_TASK_ID}q;d" ./petropoulos_accessions)

salmon quant -i rds-asg/salmon_indexes/hg19_cdna -l SF -r rds-asg/petropoulos_fastq/$acc.fastq.gz --validateMappings -o rds-asg/petropoulos_counts/$acc
