#!/bin/bash --login
#$ -cwd
#$ -e ./my-rds-asg/err
#$ -o ./my-rds-asg/out
#$ -t 1-125

module load apps/binapps/sra/2.10.7
module load tools/env/proxy

acc=$(sed "${SGE_TASK_ID}q;d" ./my-rds-asg/accessions)
# No prefetch due to limited disk space
fastq-dump --gzip --outdir ./rds-asg/zhou_fastq $acc

