#!/bin/bash --login
#$ -cwd
#$ -e ./err/call
#$ -o ./out/call

module load apps/binapps/gatk/4.1.8.0

#acc=$(sed "${SGE_TASK_ID}q;d" ./petropoulos_accessions)

#gatk AddOrReplaceReadGroups -I "scratch/petropoulos_bam/${acc}.bam" -O "scratch/tmp/${acc}-rg.bam" -LB petropoulos -PL ILLUMINA -PU petropoulos -SM $acc
#gatk MarkDuplicates -I "scratch/tmp/${acc}-rg.bam" -O "scratch/tmp/${acc}-marked.bam" -M "scratch/tmp/${acc}_dup_metrics" -ASO coordinate
gatk SplitNCigarReads --java-options '-Xmx4g -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1' -R rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa -I "scratch/tmp/ERR1042488-marked.bam" -O "scratch/tmp/ERR1042488-split.bam"
#rm "scratch/tmp/${acc}-marked.bam"
#gatk HaplotypeCaller -R rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa -I "scratch/tmp/${acc}-split.bam" -O "scratch/tmp/${acc}-calls.vcf.gz" -bamout "scratch/tmp/${acc}-realigned.bam"
#gatk IndexFeatureFile -I "scratch/tmp/${acc}-calls.vcf.gz"
