#!/bin/bash --login
#$ -cwd
#$ -e ./err/call
#$ -o ./out/call
#$ -t 1-25
#$ -l mem256

module load apps/binapps/gatk/4.1.8.0

unset _JAVA_OPTIONS

chr=$(sed "${SGE_TASK_ID}q;d" ./chromosomes.list)

rm -rf "scratch/gdb${chr}"

gatk GenomicsDBImport --java-options '-XX:ConcGCThreads=1 -Xmx8G -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1 -XX:+UseConcMarkSweepGC' --genomicsdb-shared-posixfs-optimizations --genomicsdb-workspace-path "scratch/gdb${chr}" -L $chr --tmp-dir scratch/tmp --sample-name-map vcf_list --max-num-intervals-to-import-in-parallel 1 --batch-size 10 --verbosity DEBUG
