#!/bin/bash --login
#$ -cwd
#$ -e ./err/call
#$ -o ./out/call

module load apps/binapps/gatk/4.1.8.0

unset _JAVA_OPTIONS

#chr=$(sed "${SGE_TASK_ID}q;d" ./chromosomes.list)

gatk GenotypeGVCFs --java-options '-XX:ConcGCThreads=1 -Xmx4G -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1' -V gendb://scratch/gdb -R rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa -O scratch/petropoulos.vcf.gz
