#!/bin/bash --login
#$ -cwd
#$ -e ./err/index
#$ -o ./out/index

module load apps/binapps/gatk/4.1.8.0
module load apps/samtools/1.9

gatk CreateSequenceDictionary -R rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa -O rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.dict
samtools faidx rds-asg/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
