#!/bin/bash --login
#$ -cwd
#$ -e ./err/split
#$ -o ./out/split
#$ -t 1-125

module load apps/fastx/0.0.14
module load apps/binapps/sra
module load tools/env/proxy2

acc=$(sed "${SGE_TASK_ID}q;d" ./my-rds-asg/accessions)
geo=$(sed "${SGE_TASK_ID}q;d" ./my-rds-asg/geo_accessions)

#list_file="./rds-asg/zhou_ref/${geo}*"
fixed_list_file="./rds-asg/zhou_ref/${acc}.list"

prefix_b="./scratch/b/${acc}_"

fastq_file="./rds-asg/zhou_fastq/${acc}.fastq.gz"

#awk -F $'\t' ' { t = $1; $1 = $2; $2 = t; print; } ' OFS=$'\t' $list_file > $fixed_list_file

zcat $fastq_file | fastx_barcode_splitter.pl --bol --bcfile $fixed_list_file --prefix $prefix_b --suffix ".fq"

